# Generated by Django 4.0.3 on 2022-08-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('itemimage', models.TextField(max_length=0)),
                ('itemprice', models.IntegerField()),
                ('itemdescription', models.TextField(max_length=225)),
            ],
        ),
    ]
