# Generated by Django 4.0.3 on 2022-08-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0002_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemimage',
            field=models.CharField(max_length=50),
        ),
    ]
