# Generated by Django 4.0.3 on 2022-08-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0003_alter_items_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itemrating',
            field=models.IntegerField(default=5),
        ),
    ]
