# Generated by Django 4.0.3 on 2022-08-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0005_purchase_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
